### ISSUE TITLE
LASTRESPONSE handling is broken

### ISSUE THREAD

**Issue by stickfigure** [paypal/PayPal-Java-SDK#118]
In the 1.2.6 branch, 400 errors throw an exception "See PayPalResource.LASTRESPONSE" for details.

However, you only set LASTRESPONSE *after* the call is made... which never happens because an exception was thrown. So the LASTRESPONSE always contains the response from the previous call, not the call that produced the error.

**Comment by juwlee** [comment]
@stickfigure `LASTRESPONSE` should capture the response after the call because there is no response *before the call*. To help your investigation, try set the debug level to `DEBUG`. It should log request/response body (if received) & headers if the environment is not `LIVE`. That would also provide a full curl command you could try out and see what the API returns. It is a handy feature to find out whether an issue is on API or on SDK.

**Comment by stickfigure** [comment]
Perhaps I chose my wording poorly.

Your code which sets LASTRESPONSE will never be called. PayPalResource.java line 406 (v1.2.6 branch):

	LASTREQUEST.set(apiCallPreHandler.getPayLoad());
	responseString = httpConnection.execute(null,
			apiCallPreHandler.getPayLoad(), headers);
	LASTRESPONSE.set(responseString);

On error, execute() throws an exception and LASTRESPONSE is never set.

**Comment by juwlee** [comment]
@stickfigure unfortunately, it is a bit tricky to get the response body through stream under `4xx` error due to underlying Java's behavior. See [here](http://stackoverflow.com/questions/6070350/errorstream-in-httpurlconnection). Please try my suggestion above instead.

**Comment by stickfigure** [comment]
It's not tricky at all. Here's the code:

	final InputStream content = conn.getErrorStream() != null ? conn.getErrorStream() : conn.getInputStream();

I had this code working (and correctly reporting the error content) in my fork of 1.2.5 before I upgraded to 1.2.6.
