### ISSUE TITLE
Article 2 after completion of a cycle of payment deductions record

### ISSUE THREAD

**Issue by heikehuan** [paypal/PayPal-Java-SDK#185]
### General Information

- Mode (Sandbox/Live):Sandbox
- PayPal-Debug-ID(s) (from any logs):  I-FVSAT69ECAJT
- Version of Java used:1.8
- SDK Version:1.4.2

### Issue Description

> when I create a bill plan , and execute the agreement, I login the saler's account, I find 2 records of the fee. 2 same fee list, I think it should be only one.

**Comment by ppmtscory** [comment]
This will happen if you are setting the `setup_fee` and also setting the agreement to start immediately.  When doing so, the `setup_fee` will charge right away and, since the agreement is set to start immediately, that first charge is also taken.  If you are doing a `setup_fee`, then you'll want to set your `start_date` to a later date so that they aren't charged twice upfront if that's not what you are looking to do.
