### ISSUE TITLE
what should I set startDate when I create an agreement?

### ISSUE THREAD

**Issue by heikehuan** [paypal/PayPal-Java-SDK#193]
### General Information

- Mode (Sandbox/Live): live
- PayPal-Debug-ID(s) (from any logs):
- Version of Java used: 1.8
- SDK Version: 1.6.0

### Issue Description

> When I create an agreement Object, what should I set the parameter startDate?
And what is the startDate, the next pay time? or current time?
My code like this:

```
// first, set up plan to be included in the agreement
Plan plan = new Plan();
plan.setId("P-0V2939118D268823YFYLVH4Y");

// construct an agreement and add the above plan to it
Agreement agreement = new Agreement();
agreement.setPlan(plan);
agreement.setStartDate("2016-06-20T17:19:00z");
agreement = agreement.create(TokenHolder.accessToken);
```

**Comment by ppmtscory** [comment]
The starteDate is the date that you want the agreement to start.  Therefore, this would be when it officially becomes active and the first payment will be taken.  If you're utilizing a setup fee, then you'd just want to coordinate your startDate with that so that your customers are not being double charged right away.  Otherwise, if you're setting up a monthly subscription that you want to start at signup with the first payment, then you'd set the start date to that current date/time.
