### ISSUE TITLE
Maven: Jar and source code missmatch

### ISSUE THREAD

**Issue by silentsnooc** [paypal/PayPal-Java-SDK#229]
To make sure it's not a problem of having different versions of the SDK in my repository, I deleted `.m2/repository/com/paypal` and downloaded only `1.9.2` from the Maven central:

``` xml
<!-- https://mvnrepository.com/artifact/com.paypal.sdk/rest-api-sdk -->
<dependency>
    <groupId>com.paypal.sdk</groupId>
    <artifactId>rest-api-sdk</artifactId>
    <version>1.9.2</version>
</dependency>
```

Since I'm currently having [a problem patching a billing plan](http://stackoverflow.com/questions/38642140/billing-plan-patch-http-400-invalid-path-provided) I wanted to debug the generated Java code from the PayPal SDK. 

However, it appears that the debug information delivered is wrong as you can see from the screenshot:

![capture](https://cloud.githubusercontent.com/assets/1429426/17222077/d9664b5a-54f6-11e6-8092-84baf4222561.PNG)

The header of the file states:

``` java
// Generated by delombok at Mon Jul 25 15:20:43 CDT 2016
package com.paypal.api.payments;
```

**Comment by jaypatel512** [comment]
Hey @silentsnooc !

We did recently introduced lombok to autogenerate getter setters for us. We use `delombok` to generate source.jar. I will try and reproduce this issue, and see if we can get this fixed. I think the issue could be because of https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/lombok.config#L2.

Enabling it, adds a `@javax.annotation.Generated` annotation on top of each generated getter setters. 

Just curious, by how many lines are you seeing the source out of sync ? Is it fixed for all files, or is it random ? 

Thanks.

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
