### ISSUE TITLE
can't find the correct payment options

### ISSUE THREAD

**Issue by aCoder2013** [paypal/PayPal-Java-SDK#263]
### General Information

- Mode (Sandbox/Live): live
- PayPal-Debug-ID(s) (from any logs): 63f8cf7fab326
- Version of Java used: 1.8
- SDK Version: 1.13.0

### Issue Description

I created a payment,and i access the approval_url，and there is a 400 badrequest  of `https://www.paypal.com/webapps/hermes/api/batch/setbuyer`,it looks like i must have a CREDIT_CARD,but business account has been set to accept CREDIT_CARD,can't you help with this please?
PS: both the seller and customer accounts are from china
![image](https://cloud.githubusercontent.com/assets/7877752/21376603/4b3a758e-c771-11e6-9c7a-12d73f6c16b2.png)

**Comment by sguryev** [comment]
@aCoder2013 what was the issue? 
I'm doing the same in the sandbox. I have created the ExperienceProfile with ` "landing_page_type": "Billing"` in order to get the direct credit card payment feature (not sure if it's important actually.)

I'm using the Express Checkout adv. server integration flow
https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/advanced-integration/

Here is the client side part:
![image](https://cloud.githubusercontent.com/assets/6978458/22181624/da61e024-e0a0-11e6-8906-159dba15b1cd.png)

For testing I'm using the sandbox **PERSONAL account with the $1 balance in order to check the insufficient funds flow.** 

First payment try works as expected: it suggests me to input the CC info or login. 
![image](https://cloud.githubusercontent.com/assets/6978458/22181651/59ed562a-e0a1-11e6-9ecf-311e6004bd84.png)

I'm choosing the login and then it suggests me to enter the CC info again (I think because of the insufficient funds)
![image](https://cloud.githubusercontent.com/assets/6978458/22181642/415d56e6-e0a1-11e6-8f86-4dfb323c0da6.png)

This is the end and I'm clicking the cancel link in the bottom of the **browser window**. It closes the **window** and calls the `onCancel` handler in the client-side.

Now I'm clicking the checkout button again and it opens the **modal** (since I'm already logged in) and call the `payment` handler with the ajax call to the server. 

After that in Console\Network I'm seeing the 400 response:
![image](https://cloud.githubusercontent.com/assets/6978458/22181693/32782a74-e0a2-11e6-82bb-0bbbe8b984dd.png)
With the content:
![image](https://cloud.githubusercontent.com/assets/6978458/22181708/70e7b612-e0a2-11e6-9e3b-b885a22ba103.png)

After that **modal popup** is turned out to the **browser window** and it calls the `payment` handler one more time. Which causes the second payment creation and in my server flow - new Order DB entity creation (also goods reservation, etc.)

**So the questions is: why does it call the payment handler one more time?**

Thank you!

**Comment by aCoder2013** [comment]
well，mine problem is because you just can't transfer between two Chinese accounts,i solved it by using an American one

**Comment by vitaliy-kuzmich** [comment]
up: experiencing similar issue with production as a client, with same URL, but response data different. Paypal suppport does not care for me, they are responding like a bots that I should clear cache, but I tried 2 different browsers and 2 different operating systems. Any Ideas ?

**Comment by aCoder2013** [comment]
@vitaliy-kuzmich  i don't know if this can help you ,but in my case it was because paypal just doesn't support trade between china accounts

**Comment by vitaliy-kuzmich** [comment]
@aCoder2013  thanks, but it was working month ago, after suddenly I lost possibility to buy through paypal. I've opened new ticket https://github.com/paypal/paypal-checkout/issues/718
