### ISSUE TITLE
Express Checkout

### ISSUE THREAD

**Issue by maniJoe** [paypal/PayPal-Java-SDK#288]
@pp-randy 

i am doing a poc on Express checkout checkout.js plugin.

i need to get payment id before payment initiates.
is this possible?

**Comment by pp-randy** [comment]
@maniJoe are you following the [ CheckoutJS Basic client integration](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/basic-integration/)? 

If so you could grab this in your payment function. Since paypal.rest.payments.create is a Promise you can add a .then to get the value first then return it.
```
payment: function() {

            var env    = this.props.env;
            var client = this.props.client;

            return paypal.rest.payment.create(env, client, {
                transactions: [
                    {
                        amount: { total: '1.00', currency: 'USD' }
                    }
                ]
            })
           .then(function(payment){
                //get value from payment here
                 return payment;
            });
        }
```

**Comment by maniJoe** [comment]
@pp-randy 

Thanks a lot it worked for me

**Comment by maniJoe** [comment]
@pp-randy 

                  I have some clarifications on payment methods.

                  1. What are the payment methods available in PayPal?
                  2. are payment methods the interface through which we do payments?
                  3. Merits & demerits of express checkout?
                  4. is PayPal checkout a page based payment?
                  5. is PayPal express check out a model based payment?

             Could you please clarify this?

**Comment by pp-randy** [comment]
Since your issue is resolved I am closing the issue.  However, we can still discuss more if you wish.

You can be some answers here: https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/
> Express Checkout gives your buyers a simplified checkout experience that keeps them local to your website throughout the payment authorization process and lets them use their PayPal balance, bank account, or credit card to pay without sharing or entering any sensitive information on your site.

I'm not sure what you mean by page or model based.  Can you elaborate on those questions?
